# Generated by Django 3.2.3 on 2021-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
